In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1337)

In [14]:
embed_table=nn.Embedding(10, 10)

In [16]:
logits = embed_table(torch.tensor([0, 1]))
print(logits)


tensor([[ 0.1808, -0.0700, -0.3596, -0.9152,  0.6258,  0.0255,  0.9545,  0.0643,
          0.3612,  1.1679],
        [-1.3499, -0.5102,  0.2360, -0.2398, -0.9211,  1.5433,  1.3488, -0.1396,
          0.2858,  0.9651]], grad_fn=<EmbeddingBackward0>)


In [18]:
import torch
import torch.nn.functional as F

# 假设有一个简单的批次，包括三个样本，每个样本属于三个类别之一
logits = torch.tensor([[1.0, 2.0, 0.1], [1.2, 0.8, 1.5], [2.0, 1.0, 0.5]])
labels = torch.tensor([1, 0, 2])

# 1. 计算softmax
softmax = torch.softmax(logits, dim=1)
print("Softmax:\n", softmax)

# 2. 取对应标签的概率
# 我们需要用gather方法来选择每个样本中对应真实标签的概率
# 这里的gather方法用来按照标签索引提取概率
labels = labels.view(-1, 1)  # 将labels调整为列向量
probs = softmax.gather(1, labels).squeeze()
print("Probs:\n", probs)

# 3. 计算负对数似然
neg_log_likelihood = -torch.log(probs)
print("Negative Log-Likelihood:\n", neg_log_likelihood)

# 4. 求均值，得到最终的交叉熵损失
loss = neg_log_likelihood.mean()
print("Cross Entropy Loss:\n", loss)

# 使用PyTorch的cross_entropy函数进行验证
cross_entropy_loss = F.cross_entropy(logits, labels.view(-1))
print("PyTorch Cross Entropy Loss:\n", cross_entropy_loss)


Softmax:
 tensor([[0.2424, 0.6590, 0.0986],
        [0.3311, 0.2219, 0.4469],
        [0.6285, 0.2312, 0.1402]])
Probs:
 tensor([0.6590, 0.3311, 0.1402])
Negative Log-Likelihood:
 tensor([0.4170, 1.1053, 1.9644])
Cross Entropy Loss:
 tensor(1.1622)
PyTorch Cross Entropy Loss:
 tensor(1.1622)


In [19]:
print(labels)

tensor([[1],
        [0],
        [2]])


In [20]:
from text_gen import TextGenerator
text_gen = TextGenerator()

loading input.txt ... 


In [22]:
text_gen.generate(input_text="h")

IndexError: too many indices for tensor of dimension 2

In [25]:
xs = text_gen.tokenizer.encode("i")
xs = torch.tensor([xs])
ys = text_gen.model.generate(xs, max_new_token=10)
print(ys)

tensor([[47, 40, 24, 12, 55, 28,  7, 29, 35, 49, 58]])


In [26]:
query=nn.Linear(32, 16)
x = torch.rand(8, 32)
q = query(x)
print(q.shape)

torch.Size([8, 16])
